version: '3'

services:
  web:
    image: openconceptlab/oclweb3:${TAG-dev}
    build:
      context: .
      target: build
      args:
        NODE_ENV: development
    ports:
      - "4002:4002"
      - "4003:35729"
      - "6007:6006"
    restart: on-failure
    volumes:
      - .:/app:z
    environment:
      - LOGIN_REDIRECT_URL=${LOGIN_REDIRECT_URL-http://localhost:4002}
      - OIDC_RP_CLIENT_ID=${OIDC_RP_CLIENT_ID-ocllocal}
      - OIDC_RP_CLIENT_SECRET
