name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add GITHUB_SHA_SHORT env property with commit short sha
      run: echo "GITHUB_SHA_SHORT=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag openconceptlab/oclweb3:nightly --tag openconceptlab/oclweb3:3.0-alpha-${GITHUB_SHA_SHORT}
